name = "FIB"
uuid = "13b007ba-0ca8-5af2-9adf-bc6a6301e25a"
repo = "https://github.com/JuliaPOMDP/FIB.jl"
version = "0.4.4"

[deps]
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
POMDPLinter = "0.1"
POMDPTools = "0.1"
POMDPs = "0.9, 1"
julia = "1"

[extras]
POMDPLinter = "f3bd98c0-eb40-45e2-9eb1-f2763262d755"
POMDPModels = "355abbd5-f08e-5560-ac9e-8b5f2592a0ca"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["POMDPModels", "POMDPLinter", "Test"]
